<template>
  <div class="about">
     <textarea name="" id="" cols="30" rows="10" v-model="txt1"></textarea>
     <textarea name="" id="" cols="30" rows="10" v-model="txt2"></textarea>
     <div v-html="prettyHtml" />
  </div>
</template>


<script>
import * as Diff2Html from 'diff2html';
import 'diff2html/bundles/css/diff2html.min.css';
const Diff = require('diff');
import { csv2md } from 'csv2md'
import * as CSV from 'csv-string';

export default {
  data() {
    return {
      diffs:
        '--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n',
      txt1: "test",
      txt2: "tests",
   
      
    };
  },
  computed: {
    prettyHtml() {
      //convert string from TSV to CSV
      // with String
      const arr = CSV.parse('a,b,c\na,b,c');
      const str = CSV.stringify(arr);

      const csv1 = CSV.stringify(CSV.parse(this.txt1))
      const csv2 = CSV.stringify(CSV.parse(this.txt2))
      console.log(arr)
      console.log(str)

      let markdown1 = csv2md(csv1, {
        pretty: true
      })
      let markdown2 = csv2md(csv2, {
        pretty: true
      })

      const diff = Diff.createTwoFilesPatch("file", "file", markdown1, markdown2);

      
      
      

      return Diff2Html.html(diff, {
        inputFormat: 'diff',
        drawFileList: true,
        matching: 'lines',
        outputFormat: 'side-by-side',
      });
    },
  },
}
</script>